version: '3.9'

services:
  product_nginx:
    image: nginx:alpine
    container_name: product_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - product_app
      - product_db
    networks:
      - shopping

  product_db:
    image: postgres
    container_name: product_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Product
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - shopping
  product_app:
    container_name: product_app
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - shopping

  product_pgadmin:
    image: dpage/pgadmin4
    container_name: product_pgadmin
    ports:
      - "5050:80"
    depends_on:
      - product_db
    environment:
      PGADMIN_DEFAULT_EMAIL: ibrahimkhalaf99@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - shopping

networks:
  shopping:
    external: true